local matchanovel = require "matchanovel.matchanovel"
local save = require "matchanovel.save"
local settings = require "matchanovel.settings"

function init(self)
	math.randomseed(socket.gettime()*10000)
	matchanovel.init("/assets/scripts/script.txt")
end

function update(self, dt)
	save.update(dt)
	settings.check_updates()
end

function on_message(self, message_id, message, sender)
end

function on_input(self, action_id, action)
	--    msg.post(".", "acquire_input_focus")
end
